In [9]:
#This file contains the first 25 Fibonacci numbers in its only column. 
#Add the next 25 fibonacci numbers into the DataFrame. 
#A fibonacci number is a sequence where the current number is the sum of previous two numbers in the sequence.
import pandas as pd
fib = pd.read_csv('fibonacci.csv')
fib

    Fibonacci
0           0
1           1
2           1
3           2
4           3
5           5
6           8
7          13
8          21
9          34
10         55
11         89
12        144
13        233
14        377
15        610
16        987
17       1597
18       2584
19       4181
20       6765
21      10946
22      17711
23      28657
24      46368

In [4]:
fib1=pd.Series(0*25,index=range(25,51))

fib1[25]=fib.iloc[23]['Fibonacci']+fib.iloc[24]['Fibonacci']
fib1[26]=fib.iloc[24]['Fibonacci']+fib1[25]
for i in range(27,51):
    fib1[i]=fib1[i-2]+fib1[i-1]
fib1

25          75025
26         121393
27         196418
28         317811
29         514229
30         832040
31        1346269
32        2178309
33        3524578
34        5702887
35        9227465
36       14930352
37       24157817
38       39088169
39       63245986
40      102334155
41      165580141
42      267914296
43      433494437
44      701408733
45     1134903170
46     1836311903
47     2971215073
48     4807526976
49     7778742049
50    12586269025
dtype: int64

In [13]:
df = pd.concat([fib, fib1])
for i in range(25,51):
    df.iloc[i]['Fibonacci']=df.iloc[i][0]

C:\Users\anna_\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [8]:
i=0
for i in range(25):
    fib.append(fib.loc[len(fib)-1]+fib.loc[len(fib)-2], ignore_index=True)
fib

    Fibonacci
0           0
1           1
2           1
3           2
4           3
5           5
6           8
7          13
8          21
9          34
10         55
11         89
12        144
13        233
14        377
15        610
16        987
17       1597
18       2584
19       4181
20       6765
21      10946
22      17711
23      28657
24      46368

In [10]:
#iloc doesn't work for assigning
#for i in range(25):
    #fib.iloc[25+i]=fib.iloc[len(fib)-1]+fib.iloc[len(fib)-2]
#fib

IndexError: single positional indexer is out-of-bounds